context:
  version: "1.16.0"

package:
  name: nickel
  version: ${{ version }}

source:
  url: https://github.com/tweag/nickel/archive/${{ version }}.tar.gz
  sha256: 32a449ebc4d463dd193eb8ce8aced5324655188095e709a9c0addb7b3ceeaec3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - nickel --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Better configuration for less
  homepage: https://github.com/tweag/nickel
  repository: https://github.com/tweag/nickel

extra:
  recipe-maintainers:
    - danielnachun
