context:
  version: "1.18.0"

package:
  name: nickel
  version: ${{ version }}

source:
  url: https://github.com/tweag/nickel/archive/${{ version }}.tar.gz
  sha256: ddcac13684c1fc174a45e0e179ff4ef9433eb08f08bbf4b386dc722cf64ab2d5

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - nickel --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Better configuration for less
  homepage: https://github.com/tweag/nickel
  repository: https://github.com/tweag/nickel

extra:
  recipe-maintainers:
    - danielnachun
