context:
  version: "1.9.1"

package:
  name: nickel
  version: ${{ version }}

source:
  url: https://github.com/tweag/nickel/archive/${{ version }}.tar.gz
  sha256: a775ef5ec0f375fa75f9fbe146f4b5c9bbf8728b39ac73fd0685f32b956e5c99

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - nickel --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Better configuration for less
  homepage: https://github.com/tweag/nickel
  repository: https://github.com/tweag/nickel

extra:
  recipe-maintainers:
    - danielnachun
