context:
  version: "1.17.0"

package:
  name: nickel
  version: ${{ version }}

source:
  url: https://github.com/tweag/nickel/archive/${{ version }}.tar.gz
  sha256: 8cc47b3a2b9ed4e3b7fca06f36a8a295d231e9f8bb112d0cc02081583c189f75

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - nickel --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Better configuration for less
  homepage: https://github.com/tweag/nickel
  repository: https://github.com/tweag/nickel

extra:
  recipe-maintainers:
    - danielnachun
